
naturalistic_assay_configuration = [
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "prey_only",
        "Assay Configuration Name": "Naturalistic",
        "Trial Number": 5,
        "Run Mode": "Assay",
        "Priority": 1,
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "set random seed": False,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "behavioural choice"],
                "ablations": []
            },
        ]
    }
]

behavioural_data_config = [
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "prey_only",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Trial Number": 3,
        "Run Mode": "Assay",
        "Priority": 2,
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "set random seed": False,
        "Assays": [
            {
                "assay id": "Prey-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Prey-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Prey-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Prey-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Prey-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Prey-6",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Prey-7",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Prey-8",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Prey-9",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Prey-10",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
        ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "naturalistic",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Trial Number": 3,
        "Run Mode": "Assay",
        "Priority": 1,
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "set random seed": False,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-6",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-7",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-8",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-9",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-10",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },

        ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "predator_heavy",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Trial Number": 3,
        "Run Mode": "Assay",
        "Priority": 1,
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "set random seed": False,
        "Assays": [
            {
                "assay id": "Predator-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-6",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-7",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-8",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-9",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-10",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
        ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "naturalistic",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Trial Number": 4,
        "Run Mode": "Assay",
        "Priority": 1,
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "set random seed": False,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-6",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-7",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-8",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-9",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-10",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },

        ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "predator_heavy",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Trial Number": 4,
        "Run Mode": "Assay",
        "Priority": 1,
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "set random seed": False,
        "Assays": [
            {
                "assay id": "Predator-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-6",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-7",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-8",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-9",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
            {
                "assay id": "Predator-10",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle"],
                "ablations": []
            },
        ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "naturalistic",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Trial Number": 5,
        "Run Mode": "Assay",
        "Priority": 1,
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "set random seed": False,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-6",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-7",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-8",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-9",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-10",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },

        ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "naturalistic",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Trial Number": 6,
        "Run Mode": "Assay",
        "Priority": 1,
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "set random seed": False,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-6",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-7",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-8",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-9",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-10",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },

        ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "naturalistic",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Trial Number": 7,
        "Run Mode": "Assay",
        "Priority": 1,
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "set random seed": False,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-6",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-7",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-8",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-9",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-10",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": False,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                               "prey_positions", "predator_position", "fish_angle", "rnn state"],
                "ablations": []
            },

        ]
    },
]


empty_environment_config = [
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "prey_low_density",
        "Assay Configuration Name": "Empty-Environment",
        "Trial Number": 5,
        "Run Mode": "Assay",
        "Priority": 2,
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "set random seed": False,
        "Assays": [
            {
                "assay id": "Empty-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": False,
                "recordings": ["behavioural choice", "position", "fish_angle", "predator", "prey_positions", "rnn state"],
                "ablations": []
            },
            ]
    }
]

controlled_assay_configuration_2 = [
    {
        "Model Name": "basic_all_features",
        "Environment Name": "test_square",
        "Trial Number": 1,
        "Assay Configuration Name": "Controlled_Visual_Stimuli",
        "Run Mode": "Assay",
        "Realistic Bouts": False,
        "Using GPU": True,
        "monitor gpu": True,
        "Priority": 1,
        "Assays": [
            {
                "assay id": "Moving-Prey",
                "stimulus paradigm": "Projection",
                "duration": 241,
                "Tethered": True,
                "save frames": True,
                "recordings": ["behavioural choice", "rnn state", "observation"],
                "stimuli": {
                    "prey 1": [
                        {"step": 0,
                         "position": [150, 150]},
                        {"step": 40,
                         "position": [450, 150]},
                        {"step": 80,
                         "position": [450, 450]},
                        {"step": 120,
                         "position": [150, 450]},
                        {"step": 160,
                         "position": [450, 450]},
                        {"step": 200,
                         "position": [450, 150]},
                        {"step": 240,
                         "position": [150, 150]},
                    ],
                },
                "interactions": []},
{
                "assay id": "Moving-Predator",
                "stimulus paradigm": "Projection",
                "duration": 121,
                "Tethered": True,
                "save frames": True,
                "recordings": ["behavioural choice", "rnn state", "observation"],
                "stimuli": {
                    "predator 1": [
                        {"step": 0,
                         "position": [100, 100]},
                        {"step": 20,
                         "position": [500, 100]},
                        {"step": 40,
                         "position": [500, 500]},
                        {"step": 60,
                         "position": [100, 500]},
                        {"step": 80,
                         "position": [500, 500]},
                        {"step": 100,
                         "position": [500, 100]},
                        {"step": 120,
                         "position": [100, 100]},
                    ],
                },
                "interactions": []},
        ]
    },
    {
        "Model Name": "realistic_all_features",
        "Environment Name": "test_square",
        "Trial Number": 2,
        "Assay Configuration Name": "Controlled_Visual_Stimuli",
        "Run Mode": "Assay",
        "Realistic Bouts": True,
        "Using GPU": True,
        "monitor gpu": True,
        "Priority": 1,
        "Assays": [
            {
                "assay id": "Moving-Prey",
                "stimulus paradigm": "Projection",
                "duration": 241,
                "Tethered": True,
                "save frames": True,
                "recordings": ["behavioural choice", "rnn state", "observation"],
                "stimuli": {
                    "prey 1": [
                        {"step": 0,
                         "position": [150, 150]},
                        {"step": 40,
                         "position": [450, 150]},
                        {"step": 80,
                         "position": [450, 450]},
                        {"step": 120,
                         "position": [150, 450]},
                        {"step": 160,
                         "position": [450, 450]},
                        {"step": 200,
                         "position": [450, 150]},
                        {"step": 240,
                         "position": [150, 150]},
                    ],
                },
                "interactions": []
            },
            {
                "assay id": "Moving-Predator",
                "stimulus paradigm": "Projection",
                "duration": 121,
                "Tethered": True,
                "save frames": True,
                "recordings": ["behavioural choice", "rnn state", "observation"],
                "stimuli": {
                    "predator 1": [
                        {"step": 0,
                         "position": [100, 100]},
                        {"step": 20,
                         "position": [500, 100]},
                        {"step": 40,
                         "position": [500, 500]},
                        {"step": 60,
                         "position": [100, 500]},
                        {"step": 80,
                         "position": [500, 500]},
                        {"step": 100,
                         "position": [500, 100]},
                        {"step": 120,
                         "position": [100, 100]},
                    ],
                },
                "interactions": []},
        ]
    },
]


