import json
import random

predator_response_vector = {
        "Model Name": "even_prey_ref",
        "Environment Name": "test_square",
        "Trial Number": 5,
        "Assay Configuration Name": "Predator-Full-Response-Vector",
        "Run Mode": "Assay",
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "set random seed": False,
        "Priority": 1,
        "Assays": [
            {
                "assay id": "Predator-Static-40",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": False,
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 40,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Predator-Static-60",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": False,
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 60,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Predator-Static-80",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": False,
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 80,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Predator-Left-40",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Left",
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 40,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Predator-Left-60",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Left",
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 60,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Predator-Left-80",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Left",
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 80,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Predator-Right-40",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Right",
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 40,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Predator-Right-60",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Right",
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 60,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Predator-Right-80",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Right",
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 80,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Predator-Away",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Away",
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 80,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Predator-Towards",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Towards",
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 40,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Predator-Static-40",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": False,
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 40,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Predator-Static-60",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": False,
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 60,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Predator-Static-80",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": False,
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 80,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Predator-Left-40",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Left",
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 40,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Predator-Left-60",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Left",
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 60,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Predator-Left-80",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Left",
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 80,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Predator-Right-40",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Right",
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 40,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Predator-Right-60",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Right",
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 60,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Predator-Right-80",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Right",
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 80,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Predator-Away",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Away",
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 80,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Predator-Towards",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Towards",
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "predator 1": {"steps": 550,
                                   "size": 40,
                                   "interval": 50,
                                   },
                },
                "ablations": []
            }
        ]
    }
prey_response_vector = {
        "Model Name": "even_prey_ref",
        "Environment Name": "test_square",
        "Trial Number": 5,
        "Assay Configuration Name": "Prey-Full-Response-Vector",
        "Run Mode": "Assay",
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "set random seed": False,
        "Priority": 1,
        "Assays": [
            {
                "assay id": "Prey-Static-5",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": False,
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 5,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Prey-Static-10",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": False,
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 10,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Prey-Static-15",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": False,
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 15,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Prey-Left-5",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Left",
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 5,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Prey-Left-10",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Left",
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 10,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Prey-Left-15",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Left",
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 15,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Prey-Right-5",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Right",
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 5,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Prey-Right-10",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Right",
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 10,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Prey-Right-15",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Right",
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 15,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Prey-Away",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Away",
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 15,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Prey-Towards",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Towards",
                "reset": False,
                "background": None,
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 5,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Prey-Static-5",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": False,
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 5,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Prey-Static-10",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": False,
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 10,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Prey-Static-15",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": False,
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 15,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Prey-Left-5",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Left",
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 5,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Prey-Left-10",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Left",
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 10,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Prey-Left-15",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Left",
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 15,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Prey-Right-5",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Right",
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 5,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Prey-Right-15",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Right",
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 15,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Prey-Right-15",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Right",
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 15,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Prey-Away",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Away",
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 15,
                               "interval": 50,
                               },
                },
                "ablations": []
            },
            {
                "assay id": "Background-Prey-Towards",
                "stimulus paradigm": "Projection",
                "Tethered": True,
                "set positions": False,
                "random positions": False,
                "moving": "Towards",
                "reset": False,
                "background": "Red",
                "reset interval": 100,
                "duration": 550,
                "save frames": False,
                "save stimuli": True,
                "collisions": False,
                "recordings": ["rnn state", "behavioural choice"],
                "stimuli": {
                    "prey 1": {"steps": 550,
                               "size": 5,
                               "interval": 50,
                               },
                },
                "ablations": []
            }
        ]
    }

naturalistic_configuration = {
    "Model Name": "even_prey_ref",
    "Environment Name": "naturalistic",
    "Assay Configuration Name": "Behavioural-Data-Free",
    "Trial Number": 3,
    "Run Mode": "Assay",
    "Priority": 1,
    "Realistic Bouts": True,
    "Using GPU": False,
    "monitor gpu": False,
    "set random seed": False,
    "Assays": [
        {
            "assay id": "Naturalistic-1",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": True,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": True,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle", "rnn state"],
            "ablations": []
        },
        {
            "assay id": "Naturalistic-2",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": True,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle", "rnn state"],
            "ablations": []
        },
        {
            "assay id": "Naturalistic-3",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": True,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle", "rnn state"],
            "ablations": []
        },
        {
            "assay id": "Naturalistic-4",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": True,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle", "rnn state"],
            "ablations": []
        },
        {
            "assay id": "Naturalistic-5",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": True,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle", "rnn state"],
            "ablations": []
        },
        {
            "assay id": "Naturalistic-6",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": True,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle", "rnn state"],
            "ablations": []
        },
        {
            "assay id": "Naturalistic-7",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": True,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle", "rnn state"],
            "ablations": []
        },
        {
            "assay id": "Naturalistic-8",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": True,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle", "rnn state"],
            "ablations": []
        },
        {
            "assay id": "Naturalistic-9",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": True,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle", "rnn state"],
            "ablations": []
        },
        {
            "assay id": "Naturalistic-10",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": True,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle", "rnn state"],
            "ablations": []
        },

    ]
}
predator_behaviour_configuration = {
    "Model Name": "even_prey_ref",
    "Environment Name": "predator_heavy",
    "Assay Configuration Name": "Behavioural-Data-Free",
    "Trial Number": 3,
    "Run Mode": "Assay",
    "Priority": 1,
    "Realistic Bouts": True,
    "Using GPU": False,
    "monitor gpu": False,
    "set random seed": False,
    "Assays": [
        {
            "assay id": "Predator-1",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": True,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Predator-2",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Predator-3",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Predator-4",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Predator-5",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Predator-6",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Predator-7",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Predator-8",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Predator-9",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Predator-10",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
    ]
}
prey_behaviour_configuration = {
    "Model Name": "even_prey_ref",
    "Environment Name": "prey_only",
    "Assay Configuration Name": "Behavioural-Data-Free",
    "Trial Number": 3,
    "Run Mode": "Assay",
    "Priority": 2,
    "Realistic Bouts": True,
    "Using GPU": False,
    "monitor gpu": False,
    "set random seed": False,
    "Assays": [
        {
            "assay id": "Prey-1",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": True,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Prey-2",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Prey-3",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Prey-4",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Prey-5",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Prey-6",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Prey-7",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Prey-8",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Prey-9",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
        {
            "assay id": "Prey-10",
            "stimulus paradigm": "Naturalistic",
            "duration": 1000,
            "Tethered": False,
            "save frames": False,
            "random positions": False,
            "background": None,
            "moving": False,
            "save stimuli": False,
            "reset": False,
            "collisions": False,
            "recordings": ["behavioural choice", "consumed", "predator", "observation", "position",
                           "prey_positions", "predator_position", "fish_angle"],
            "ablations": []
        },
    ]
}

placeholder_list = [0]
ablation_gradient = [
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "prey_only",
        "Trial Number": 7,
        "Assay Configuration Name": f"Ablation-Test-Configuration",
        "Run Mode": "Assay",
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "Priority": 1,
        "set random seed": True,
        "Assays": [
            {
                "assay id": "Ablated-10-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(len(placeholder_list)/10)],
            },
            {
                "assay id": "Ablated-10-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(len(placeholder_list) / 10)],
            },
            {
                "assay id": "Ablated-10-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(len(placeholder_list) / 10)],
            },
        ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "prey_only",
        "Trial Number": 7,
        "Assay Configuration Name": f"Ablation-Test-Configuration",
        "Run Mode": "Assay",
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "Priority": 1,
        "set random seed": True,
        "Assays": [
            {
                "assay id": "Ablated-20-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(len(placeholder_list)/5)],
            },
            {
                "assay id": "Ablated-20-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(len(placeholder_list) / 5)],
            },
            {
                "assay id": "Ablated-20-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(len(placeholder_list) / 5)],
            },
]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "prey_only",
        "Trial Number": 7,
        "Assay Configuration Name": f"Ablation-Test-Configuration",
        "Run Mode": "Assay",
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "Priority": 1,
        "set random seed": True,
        "Assays": [
            {
                "assay id": "Ablated-30-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(3*len(placeholder_list)/10)],
            },
            {
                "assay id": "Ablated-30-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(3 * len(placeholder_list) / 10)],
            },
            {
                "assay id": "Ablated-30-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(3 * len(placeholder_list) / 10)],
            },
            ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "prey_only",
        "Trial Number": 7,
        "Assay Configuration Name": f"Ablation-Test-Configuration",
        "Run Mode": "Assay",
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "Priority": 1,
        "set random seed": True,
        "Assays": [
            {
                "assay id": "Ablated-40-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(4*len(placeholder_list)/10)],
            },
            {
                "assay id": "Ablated-40-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(4 * len(placeholder_list) / 10)],
            },
            {
                "assay id": "Ablated-40-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(4 * len(placeholder_list) / 10)],
            },
            ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "prey_only",
        "Trial Number": 7,
        "Assay Configuration Name": f"Ablation-Test-Configuration",
        "Run Mode": "Assay",
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "Priority": 1,
        "set random seed": True,
        "Assays": [
            {
                "assay id": "Ablated-50-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(5*len(placeholder_list)/10)],
            },
            {
                "assay id": "Ablated-50-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(5 * len(placeholder_list) / 10)],
            },
            {
                "assay id": "Ablated-50-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(5 * len(placeholder_list) / 10)],
            },
            ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "prey_only",
        "Trial Number": 7,
        "Assay Configuration Name": f"Ablation-Test-Configuration",
        "Run Mode": "Assay",
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "Priority": 1,
        "set random seed": True,
        "Assays": [
            {
                "assay id": "Ablated-60-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(6*len(placeholder_list)/10)],
            },
            {
                "assay id": "Ablated-60-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(6 * len(placeholder_list) / 10)],
            },
            {
                "assay id": "Ablated-60-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(6 * len(placeholder_list) / 10)],
            },
            ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "prey_only",
        "Trial Number": 7,
        "Assay Configuration Name": f"Ablation-Test-Configuration",
        "Run Mode": "Assay",
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "Priority": 1,
        "set random seed": True,
        "Assays": [
            {
                "assay id": "Ablated-70-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(7*len(placeholder_list)/10)],
            },
            {
                "assay id": "Ablated-70-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(7 * len(placeholder_list) / 10)],
            },
            {
                "assay id": "Ablated-70-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(7 * len(placeholder_list) / 10)],
            },
            ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "prey_only",
        "Trial Number": 7,
        "Assay Configuration Name": f"Ablation-Test-Configuration",
        "Run Mode": "Assay",
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "Priority": 1,
        "set random seed": True,
        "Assays": [
            {
                "assay id": "Ablated-80-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(8*len(placeholder_list)/10)],
            },
            {
                "assay id": "Ablated-80-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(8 * len(placeholder_list) / 10)],
            },
            {
                "assay id": "Ablated-80-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(8 * len(placeholder_list) / 10)],
            },
            ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "prey_only",
        "Trial Number": 7,
        "Assay Configuration Name": f"Ablation-Test-Configuration",
        "Run Mode": "Assay",
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "Priority": 1,
        "set random seed": True,
        "Assays": [
            {
                "assay id": "Ablated-90-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(9*len(placeholder_list)/10)],
            },
            {
                "assay id": "Ablated-90-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(9 * len(placeholder_list) / 10)],
            },
            {
                "assay id": "Ablated-90-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list[:int(9 * len(placeholder_list) / 10)],
            },
            ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "prey_only",
        "Trial Number": 7,
        "Assay Configuration Name": f"Ablation-Test-Configuration",
        "Run Mode": "Assay",
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "Priority": 1,
        "set random seed": True,
        "Assays": [
            {
                "assay id": "Ablated-100-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list,
            },
            {
                "assay id": "Ablated-100-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list,
            },
            {
                "assay id": "Ablated-100-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": placeholder_list,
            },
        ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "prey_only",
        "Trial Number": 7,
        "Assay Configuration Name": f"Ablation-Test-Configuration",
        "Run Mode": "Assay",
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "Priority": 1,
        "set random seed": True,
        "Assays": [
            {
                "assay id": "Control-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": None,
            },
            {
                "assay id": "Control-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": None,
            },
            {
                "assay id": "Control-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": None,
            },
        ]
    },
    {
        "Model Name": "even_prey_ref",
        "Environment Name": "prey_only",
        "Trial Number": 7,
        "Assay Configuration Name": f"Ablation-Test-Configuration",
        "Run Mode": "Assay",
        "Realistic Bouts": True,
        "Using GPU": False,
        "monitor gpu": False,
        "Priority": 1,
        "set random seed": True,
        "Assays": [
            {
                "assay id": "Random-Control-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": list(random.sample(range(0, 512), len(placeholder_list))),
            },
            {
                "assay id": "Random-Control-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": list(random.sample(range(0, 512), len(placeholder_list))),
            },
            {
                "assay id": "Random-Control-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 500,
                "Tethered": False,
                "save frames": True,
                "random positions": False,
                "background": None,
                "moving": False,
                "save stimuli": False,
                "reset": False,
                "collisions": True,
                "recordings": ["consumed", "predator", "behavioural choice"],
                "ablations": list(random.sample(range(0, 512), len(placeholder_list))),
            },
        ]
    }
]


def build_vrv_configuration(model_names):
    configuration = []
    for model in model_names:
        pred_config = predator_response_vector.copy()
        prey_config = prey_response_vector.copy()
        pred_config["Model Name"] = model[:-2]
        pred_config["Trial Number"] = int(model[-1])
        prey_config["Model Name"] = model[:-2]
        prey_config["Trial Number"] = int(model[-1])
        configuration.append(prey_config)
        configuration.append(pred_config)
    with open(f"vrv_config.json", 'w') as f:
        json.dump(configuration, f, indent=4)


def build_naturalistic_configuration(model_names, naturalistic_config_name, predator_config_name, prey_config_name):
    configuration = []
    for model in model_names:
        nat_config = naturalistic_configuration.copy()
        pred_config = predator_behaviour_configuration.copy()
        prey_config = prey_behaviour_configuration.copy()

        nat_config["Model Name"] = model[:-2]
        nat_config["Trial Number"] = int(model[-1])
        nat_config["Environment Name"] = naturalistic_config_name

        pred_config["Model Name"] = model[:-2]
        pred_config["Trial Number"] = int(model[-1])
        pred_config["Environment Name"] = predator_config_name

        prey_config["Model Name"] = model[:-2]
        prey_config["Trial Number"] = int(model[-1])
        prey_config["Environment Name"] = prey_config_name

        configuration.append(nat_config)
        configuration.append(prey_config)
        configuration.append(pred_config)
    with open(f"behavioural_conf.json", 'w') as f:
        json.dump(configuration, f, indent=4)


def build_ablation_gradient_configuration(model_names, neuron_groups, ablation_group_names, environment):
    for graoup, neurons, model in zip(ablation_group_names, neuron_groups, model_names):
        gradient_conf_list = ablation_gradient.copy()
        for conf in gradient_conf_list:
            conf["Model Name"] = model[:-2]
            conf["Trial Number"] = int(model[-1])
            conf["Environment Name"] = environment
            conf["Assay Configuration Name"] = f"Ablation-Test-{ablation_group_names}"
            for a, assay in enumerate(conf["Assays"]):
                conf["Assays"][a] = assay
                # TODO: Find way of passing over the gradients. Should also ablate in a random way each time.


build_naturalistic_configuration(["even_prey_ref-5", "even_prey_ref_6"], "natur", "pre", "pred")
