"""File to contain all standard assay run configs applied to data."""

#####                      DQN

# Free - The same environment from training. No interventions       20 trials

dqn_free_config = [
    {
        "Model Name": "dqn_gamma",
        "Environment Name": "dqn_gamma_final",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Trial Number": 2,
        "Checkpoint": None,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": True,
        "New Simulation": True,
        "Full Reafference": True,
        "behavioural recordings": ["environmental positions", "observation"],
        "network recordings": ["rnn_shared", "internal_state"],
        "interventions": None,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-6",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-7",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-8",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-9",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-10",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-11",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-12",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-13",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-14",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-15",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-16",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-17",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-18",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-19",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-20",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            ]
    }
    ]

# Empty - An environment without predators or prey, for efficient gathering of exploration sequences    20 trials

dqn_empty_config = [
    {
        "Model Name": "dqn_gamma",
        "Environment Name": "dqn_gamma_empty",
        "Assay Configuration Name": "Behavioural-Data-Empty",
        "Trial Number": 2,
        "Checkpoint": None,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": True,
        "New Simulation": True,
        "Full Reafference": True,
        "behavioural recordings": ["environmental positions", "observation"],
        "network recordings": ["rnn_shared", "internal_state"],
        "interventions": None,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-6",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-7",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-8",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-9",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-10",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-11",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-12",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-13",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-14",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-15",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-16",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-17",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-18",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-19",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-20",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            ]
    }
    ]



