"""File to contain all standard assay run configs applied to data."""

#                      DQN

# Free - The same environment from training. No interventions


# 20 trials
dqn_free_config = [
    {
        "Model Name": "dqn_gamma",
        "Environment Name": "dqn_gamma_final",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Trial Number": 2,
        "Checkpoint": None,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": True,
        "New Simulation": True,
        "Full Reafference": True,
        "behavioural recordings": ["environmental positions", "observation"],
        "network recordings": ["rnn_shared", "internal_state"],
        "interventions": None,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-6",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-7",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-8",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-9",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-10",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-11",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-12",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-13",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-14",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-15",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-16",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-17",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-18",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-19",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-20",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            ]
    }
    ]

# 100 Trials
dqn_free_config_large = [
    {
        "Model Name": "dqn_gamma",
        "Environment Name": "dqn_gamma_final",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Trial Number": 2,
        "Checkpoint": None,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": True,
        "New Simulation": True,
        "Full Reafference": True,
        "behavioural recordings": ["environmental positions", "observation"],
        "network recordings": ["rnn_shared", "internal_state"],
        "interventions": None,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-6",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-7",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-8",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-9",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-10",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-11",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-12",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-13",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-14",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-15",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-16",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-17",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-18",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-19",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-20",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-21",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-22",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-23",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-24",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-25",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-26",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-27",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-28",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-29",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-30",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-31",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-32",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-33",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-34",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-35",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-36",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-37",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-38",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-39",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-40",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-41",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-42",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-43",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-44",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-45",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-46",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-47",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-48",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-49",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-50",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-51",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-52",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-53",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-54",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-55",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-56",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-57",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-58",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-59",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-60",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-61",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-62",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-63",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-64",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-65",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-66",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-67",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-68",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-69",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-70",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-71",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-72",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-73",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-74",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-75",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-76",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-77",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-78",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-79",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-80",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-81",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-82",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-83",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-84",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-85",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-86",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-87",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-88",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-89",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-90",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-91",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-92",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-93",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-94",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-95",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-96",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-97",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-98",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-99",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-100",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
        ]
    }
    ]


# Empty - An environment without predators or prey, for efficient gathering of exploration sequences    20 trials

dqn_empty_config = [
    {
        "Model Name": "dqn_gamma",
        "Environment Name": "dqn_gamma_empty",
        "Assay Configuration Name": "Behavioural-Data-Empty",
        "Trial Number": 2,
        "Checkpoint": None,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": True,
        "New Simulation": True,
        "Full Reafference": True,
        "behavioural recordings": ["environmental positions", "observation"],
        "network recordings": ["rnn_shared", "internal_state"],
        "interventions": None,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-6",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-7",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-8",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-9",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-10",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-11",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-12",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-13",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-14",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-15",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-16",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-17",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-18",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-19",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            {
                "assay id": "Naturalistic-20",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
            },
            ]
    }
    ]



