from Configurations.Templates.interruptions import energy_state_profile_long_term

# ========== Training Mode ==========

dqn_training_example = [
    {
        "Model Name": "dqn_training_example",
        "Environment Name": "dqn_example_configuration",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Learning Algorithm": "DQN",
    },
    {
        "Model Name": "dqn_training_example",
        "Environment Name": "dqn_example_configuration",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Learning Algorithm": "DQN",
    },
    {
        "Model Name": "dqn_training_example",
        "Environment Name": "dqn_example_configuration",
        "Trial Number": 3,
        "Run Mode": "Training",
        "Learning Algorithm": "DQN",
    },
    {
        "Model Name": "dqn_training_example",
        "Environment Name": "dqn_example_configuration",
        "Trial Number": 4,
        "Run Mode": "Training",
        "Learning Algorithm": "DQN",
    },
]

ppo_training_example = [
    {
        "Model Name": "ppo_training_example",
        "Environment Name": "ppo_example_configuration",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Learning Algorithm": "PPO",
    },
    {
        "Model Name": "ppo_training_example",
        "Environment Name": "ppo_example_configuration",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Learning Algorithm": "PPO",
    },
    {
        "Model Name": "ppo_training_example",
        "Environment Name": "ppo_example_configuration",
        "Trial Number": 3,
        "Run Mode": "Training",
        "Learning Algorithm": "PPO",
    },
    {
        "Model Name": "ppo_training_example",
        "Environment Name": "ppo_example_configuration",
        "Trial Number": 4,
        "Run Mode": "Training",
        "Learning Algorithm": "PPO",
    },
]

# ========== Assay Modes ==========

# Basic Assay (Naturalistic)

dqn_basic_assay_example = [
    {
        "Model Name": "dqn_salt_only_reduced",
        "Environment Name": "dqn_sor",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Trial Number": 1,
        "Checkpoint": 67,
        "Run Mode": "Assay",
        "Learning Algorithm": "DQN",
        "behavioural recordings": ["environmental positions"],
        "network recordings": ["rnn_shared", "internal_state"],
        "Assays": [
            {
                "assay id": "Naturalistic",
                "repeats": 2,
                "stimulus paradigm": "Naturalistic",
                "duration": 100,
                "tethered": False,
                "save frames": False,
            },
        ]
    },
]

ppo_basic_assay_example = [
    {
        "Model Name": "ppo_proj_reduced",
        "Environment Name": "ppo_proj_1",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Trial Number": 1,
        "Run Mode": "Assay",
        "Learning Algorithm": "PPO",
        "behavioural recordings": ["environmental positions"],
        "network recordings": ["rnn_shared", "internal_state"],
        "Assays": [
            {
                "assay id": "Naturalistic",
                "repeats": 2,
                "stimulus paradigm": "Naturalistic",
                "duration": 100,
                "tethered": False,
                "save frames": False,
                "use_mu": True,
            },
        ]
    },
]

# Basic Assay (Controlled Stimulus)  TODO: Create

# Basic Assay (Interventions)

dqn_interventions_assay_example = [
    {
        "Model Name": "dqn_scaffold_18",
        "Environment Name": "dqn_18_1",
        "Assay Configuration Name": "Behavioural-Data-Full-Interruptions",
        "Trial Number": 1,
        "Run Mode": "Assay",
        "Learning Algorithm": "DQN",
        "behavioural recordings": ["environmental positions"],
        "network recordings": ["rnn_shared", "internal_state"],
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "repeats": 2,
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "tethered": False,
                "save frames": False,
                "interventions": {"visual_interruptions": long_term_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": long_term_interruption_profile,
                                  "salt_interruptions": long_term_interruption_profile,
                                  "in_light_interruptions": long_term_interruption_profile,
                                  }
            },
        ]
    },
]

# Basic Assay (Ablations)  TODO: Ensure works
dqn_new_data_rnn_manipulations = [
    {
        "Model Name": "dqn_new",
        "Environment Name": "dqn_new_1",
        "Assay Configuration Name": "Behavioural-Data-RNN-Zero",
        "Trial Number": 1,
        "Checkpoint": None,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": True,
        "New Simulation": True,
        "Full Reafference": True,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-6",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-7",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-8",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-9",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-10",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-11",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-12",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-13",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-14",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-15",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-16",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-17",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-18",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-19",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-20",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },

        ],
    },
    {
        "Model Name": "dqn_new",
        "Environment Name": "dqn_new_2",
        "Assay Configuration Name": "Behavioural-Data-RNN-Zero",
        "Trial Number": 2,
        "Checkpoint": None,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": True,
        "New Simulation": True,
        "Full Reafference": True,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-6",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-7",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-8",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-9",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-10",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-11",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-12",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-13",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-14",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-15",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-16",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-17",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-18",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-19",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },
            {
                "assay id": "Naturalistic-20",
                "stimulus paradigm": "Naturalistic",
                "duration": 10000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn_shared", "internal_state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"rnn_input": rnn_zeros}
            },

        ],
    },

]



# Split Assay

dqn_split_assay_example = [
    {
        "Model Name": "dqn_0_0",
        "Environment Name": "dqn_0_1",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Trial Number": 1,
        "Run Mode": "Split-Assay",
        "Split Event": "One-Prey-Close",
        "Modification": "Nearby-Prey-Removal",
        "Learning Algorithm": "DQN",
        "behavioural recordings": ["environmental positions", "observation", "reward assessments"],
        "network recordings": ["rnn_shared", "internal_state"],
        "Assays": [
            {
                "assay id": "Naturalistic",
                "stimulus paradigm": "Naturalistic",
                "repeats": 1,
                "duration": 500,
                "tethered": False,
                "save frames": False,
            },
        ]
    }
]

ppo_split_assay_example = [
    {
        "Model Name": "ppo_proj",
        "Environment Name": "ppo_proj_1",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Trial Number": 1,
        "Run Mode": "Split-Assay",
        "Split Event": "One-Prey-Close",
        "Modification": "Nearby-Prey-Removal",
        "Learning Algorithm": "PPO",
        "behavioural recordings": ["environmental positions"],
        "network recordings": ["rnn_shared", "internal_state"],
        "Assays": [
            {
                "assay id": "Naturalistic",
                "stimulus paradigm": "Naturalistic",
                "repeats": 1,
                "duration": 500,
                "tethered": False,
                "save frames": False,
                "use_mu": True,
            },
        ]
    }
]

# Assay-Analysis-Across-Scaffold

dqn_analysis_across_scaffold_example = [
    {
        "Model Name": "dqn_0_0",
        "Environment Name": "dqn_0_1",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Config Modification": "Empty",
        "Trial Number": 1,
        "Delete Data": False,
        "Run Mode": "Assay-Analysis-Across-Scaffold",
        "Learning Algorithm": "DQN",
        "behavioural recordings": ["environmental positions"],
        "network recordings": ["rnn_shared", "internal_state"],
        "Assays": [
            {
                "assay id": "Naturalistic",
                "repeats": 1,
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "tethered": False,
                "save frames": False,
            },
        ],
        "Analysis": [
            {
                "analysis id": "Turn-Analysis",
                "analysis script": "Analysis.Behavioural.Exploration.turning_analysis_discrete",
                "analysis function": "plot_all_turn_analysis",
                "analysis arguments": ["model_name", "assay_config_name", "Naturalistic", 1],
            }
        ],
    }
]

ppo_analysis_across_scaffold_example = [
    {
        "Model Name": "ppo_proj_1",
        "Environment Name": "ppo_proj_1",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Config Modification": "Empty",
        "Trial Number": 1,
        "Run Mode": "Assay-Analysis-Across-Scaffold",
        "Learning Algorithm": "PPO",
        "behavioural recordings": ["environmental positions", "observation"],
        "network recordings": ["rnn_shared", "internal_state"],
        "Assays": [
            {
                "assay id": "Naturalistic",
                "repeats": 1,
                "stimulus paradigm": "Naturalistic",
                "duration": 1000,
                "tethered": False,
                "save frames": False,
                "use_mu": True,
            },
        ],
        "Analysis": [
            {
                "analysis id": "Turn-Analysis",
                "analysis script": "Analysis.Behavioural.Exploration.turning_analysis_continuous",
                "analysis function": "plot_all_turn_analysis_continuous",
                "analysis arguments": ["model_name", "assay_config_name", "Naturalistic", 1],
            }
        ],
    }
]
