from Configurations.Templates.interruptions import energy_state_profile_long_term, salt_profile_long_term, \
    in_light_profile_long_term, efference_A, efference_B, efference_C, efference_D, efference_E, efference_F, \
    efference_G, efference_H, efference_V, efference_W, efference_X, efference_Y, efference_Z, long_term_visual_interruption_profile


dqn_18_full_long_term_interruptions = [
    {
        "Model Name": "dqn_scaffold_18",
        "Environment Name": "dqn_18_1",
        "Assay Configuration Name": "Behavioural-Data-Full-Interruptions",
        "Trial Number": 1,
        "Checkpoint": 4200,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": False,
        "New Simulation": True,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": long_term_interruption_profile,
                                  }
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": long_term_interruption_profile,
                                  }
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": long_term_interruption_profile,
                                  }
            },
        ],
        "Full Reafference": True,
    },
]

dqn_14_full_long_term_interruptions = [
    {
        "Model Name": "dqn_scaffold_14",
        "Environment Name": "dqn_14_1",
        "Assay Configuration Name": "Behavioural-Data-Full-Interruptions2b",
        "Trial Number": 1,
        "Checkpoint": None,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": False,
        "New Simulation": True,
        "Assays": [
            # {
            #     "assay id": "Naturalistic-1",
            #     "stimulus paradigm": "Naturalistic",
            #     "duration": 2000,
            #     "Tethered": False,
            #     "save frames": True,
            #     "use_mu": True,
            #     "save stimuli": False,
            #     "random positions": False,
            #     "reset": False,
            #     "background": None,
            #     "moving": False,
            #     "collisions": True,
            #     "recordings": ["rnn state", "environmental positions", "observation", "internal state", "reward assessments"],
            #     "behavioural recordings": ["environmental positions", "observation"],
            #     "network recordings": ["rnn state", "internal state"],
            #     "energy_state_control": False,
            #     "salt_control": False,
            #     "interventions": {"visual_interruptions": long_term_interruption_profile,
            #                       "preset_energy_state": energy_state_profile_long_term,
            #                       "efference_copy_interruptions": long_term_interruption_profile,
            #                       "salt_interruptions": long_term_interruption_profile,
            #                       "in_light_interruptions": long_term_interruption_profile,
            #                       }
            # },
            # {
            #     "assay id": "Naturalistic-2",
            #     "stimulus paradigm": "Naturalistic",
            #     "duration": 2000,
            #     "Tethered": False,
            #     "save frames": True,
            #     "use_mu": True,
            #     "save stimuli": False,
            #     "random positions": False,
            #     "reset": False,
            #     "background": None,
            #     "moving": False,
            #     "collisions": True,
            #     "recordings": ["rnn state", "environmental positions", "observation", "internal state", "reward assessments"],
            #     "behavioural recordings": ["environmental positions", "observation"],
            #     "network recordings": ["rnn state", "internal state"],
            #     "energy_state_control": False,
            #     "salt_control": False,
            #     "interventions": {"visual_interruptions": long_term_interruption_profile,
            #                       "preset_energy_state": energy_state_profile_long_term,
            #                       "efference_copy_interruptions": long_term_interruption_profile,
            #                       "salt_interruptions": long_term_interruption_profile,
            #                       "in_light_interruptions": long_term_interruption_profile,
            #                       }
            # },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state", "reward assessments"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": long_term_interruption_profile,
                                  "salt_interruptions": long_term_interruption_profile,
                                  "in_light_interruptions": long_term_interruption_profile,
                                  }
            },
        ],
        "Full Reafference": False,
    },
    # {
    #     "Model Name": "dqn_scaffold_14",
    #     "Environment Name": "dqn_14_2",
    #     "Assay Configuration Name": "Behavioural-Data-Full-Interruptions2b",
    #     "Trial Number": 2,
    #     "Checkpoint": None,
    #     "Run Mode": "Assay",
    #     "Tethered": False,
    #     "Realistic Bouts": True,
    #     "Continuous Actions": False,
    #     "Learning Algorithm": "DQN",
    #     "Priority": 2,
    #     "Using GPU": True,
    #     "monitor gpu": False,
    #     "Full Logs": True,
    #     "SB Emulator": True,
    #     "set random seed": False,
    #     "New Simulation": True,
    #     "Assays": [
    #         {
    #             "assay id": "Naturalistic-1",
    #             "stimulus paradigm": "Naturalistic",
    #             "duration": 2000,
    #             "Tethered": False,
    #             "save frames": True,
    #             "use_mu": True,
    #             "save stimuli": False,
    #             "random positions": False,
    #             "reset": False,
    #             "background": None,
    #             "moving": False,
    #             "collisions": True,
    #             "recordings": ["rnn state", "environmental positions", "observation", "internal state", "reward assessments"],
    #             "behavioural recordings": ["environmental positions", "observation"],
    #             "network recordings": ["rnn state", "internal state"],
    #             "energy_state_control": False,
    #             "salt_control": False,
    #             "interventions": {"visual_interruptions": long_term_interruption_profile,
    #                               "preset_energy_state": energy_state_profile_long_term,
    #                               "efference_copy_interruptions": long_term_interruption_profile,
    #                               "salt_interruptions": long_term_interruption_profile,
    #                               "in_light_interruptions": long_term_interruption_profile,
    #                               }
    #         },
    #         {
    #             "assay id": "Naturalistic-2",
    #             "stimulus paradigm": "Naturalistic",
    #             "duration": 2000,
    #             "Tethered": False,
    #             "save frames": True,
    #             "use_mu": True,
    #             "save stimuli": False,
    #             "random positions": False,
    #             "reset": False,
    #             "background": None,
    #             "moving": False,
    #             "collisions": True,
    #             "recordings": ["rnn state", "environmental positions", "observation", "internal state", "reward assessments"],
    #             "behavioural recordings": ["environmental positions", "observation"],
    #             "network recordings": ["rnn state", "internal state"],
    #             "energy_state_control": False,
    #             "salt_control": False,
    #             "interventions": {"visual_interruptions": long_term_interruption_profile,
    #                               "preset_energy_state": energy_state_profile_long_term,
    #                               "efference_copy_interruptions": long_term_interruption_profile,
    #                               "salt_interruptions": long_term_interruption_profile,
    #                               "in_light_interruptions": long_term_interruption_profile,
    #                               }
    #         },
    #         {
    #             "assay id": "Naturalistic-3",
    #             "stimulus paradigm": "Naturalistic",
    #             "duration": 2000,
    #             "Tethered": False,
    #             "save frames": True,
    #             "use_mu": True,
    #             "save stimuli": False,
    #             "random positions": False,
    #             "reset": False,
    #             "background": None,
    #             "moving": False,
    #             "collisions": True,
    #             "recordings": ["rnn state", "environmental positions", "observation", "internal state", "reward assessments"],
    #             "behavioural recordings": ["environmental positions", "observation"],
    #             "network recordings": ["rnn state", "internal state"],
    #             "energy_state_control": False,
    #             "salt_control": False,
    #             "interventions": {"visual_interruptions": long_term_interruption_profile,
    #                               "preset_energy_state": energy_state_profile_long_term,
    #                               "efference_copy_interruptions": long_term_interruption_profile,
    #                               "salt_interruptions": long_term_interruption_profile,
    #                               "in_light_interruptions": long_term_interruption_profile,
    #                               }
    #         },
    #     ],
    #     "Full Reafference": False,
    # },
]

dqn_18_1_complete_interruptions = [
    {
        "Model Name": "dqn_scaffold_18",
        "Environment Name": "dqn_18_1",
        "Assay Configuration Name": "Interruptions-A",
        "Trial Number": 1,
        "Checkpoint": 4200,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": False,
        "New Simulation": True,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_A,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_A,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_A,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_A,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_A,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },

        ],
        "Full Reafference": True,
    },
    {
        "Model Name": "dqn_scaffold_18",
        "Environment Name": "dqn_18_1",
        "Assay Configuration Name": "Interruptions-B",
        "Trial Number": 1,
        "Checkpoint": 4200,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": False,
        "New Simulation": True,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_B,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_B,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_B,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_B,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_B,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },

        ],
        "Full Reafference": True,
    },
    {
        "Model Name": "dqn_scaffold_18",
        "Environment Name": "dqn_18_1",
        "Assay Configuration Name": "Interruptions-C",
        "Trial Number": 1,
        "Checkpoint": 4200,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": False,
        "New Simulation": True,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_C,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_C,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_C,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_C,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_C,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
        ],
        "Full Reafference": True,
    },
    {
        "Model Name": "dqn_scaffold_18",
        "Environment Name": "dqn_18_1",
        "Assay Configuration Name": "Interruptions-D",
        "Trial Number": 1,
        "Checkpoint": 4200,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": False,
        "New Simulation": True,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_D,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_D,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_D,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_D,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_D,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },

        ],
        "Full Reafference": True,
    },
    {
        "Model Name": "dqn_scaffold_18",
        "Environment Name": "dqn_18_1",
        "Assay Configuration Name": "Interruptions-E",
        "Trial Number": 1,
        "Checkpoint": 4200,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": False,
        "New Simulation": True,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_E,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_E,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_E,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_E,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_E,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
        ],
        "Full Reafference": True,
    },
    {
        "Model Name": "dqn_scaffold_18",
        "Environment Name": "dqn_18_1",
        "Assay Configuration Name": "Interruptions-F",
        "Trial Number": 1,
        "Checkpoint": 4200,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": False,
        "New Simulation": True,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_F,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_F,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_F,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_F,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_F,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
        ],
        "Full Reafference": True,
    },
    {
        "Model Name": "dqn_scaffold_18",
        "Environment Name": "dqn_18_1",
        "Assay Configuration Name": "Interruptions-G",
        "Trial Number": 1,
        "Checkpoint": 4200,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": False,
        "New Simulation": True,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_G,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_G,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_G,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_G,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_G,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
        ],
        "Full Reafference": True,
    },
    {
        "Model Name": "dqn_scaffold_18",
        "Environment Name": "dqn_18_1",
        "Assay Configuration Name": "Interruptions-H",
        "Trial Number": 1,
        "Checkpoint": 4200,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": False,
        "New Simulation": True,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_H,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_H,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_H,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_H,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": False,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "energy_state_control": False,
                "salt_control": False,
                "interventions": {"visual_interruptions": long_term_visual_interruption_profile,
                                  "preset_energy_state": energy_state_profile_long_term,
                                  "efference_copy_interruptions": efference_H,
                                  "in_light_interruptions": in_light_profile_long_term,
                                  "salt_interruptions": salt_profile_long_term,
                                  }
            },
        ],
        "Full Reafference": True,
    },
]

