
# New 17.05 onwards

dqn_scaffold_15a = [
    {
        "Model Name": "dqn_scaffold_15",
        "Environment Name": "dqn_scaffold_15",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_15",
        "Environment Name": "dqn_scaffold_15",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

ppo_scaffold_16a = [
    {
        "Model Name": "ppo_scaffold_16",
        "Environment Name": "ppo_scaffold_16",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "ppo_scaffold_16",
        "Environment Name": "ppo_scaffold_16",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

ppo_scaffold_16b = [
    {
        "Model Name": "ppo_scaffold_rvc_16",
        "Environment Name": "ppo_scaffold_rvc_16",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "ppo_scaffold_rvc_16",
        "Environment Name": "ppo_scaffold_rvc_16",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

ppo_scaffold_16c = [
    {
        "Model Name": "ppo_scaffold_sn_16",
        "Environment Name": "ppo_scaffold_sn_16",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "ppo_scaffold_sn_16",
        "Environment Name": "ppo_scaffold_sn_16",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

# new 27.05 onwards

dqn_scaffold_16a = [
    {
        "Model Name": "dqn_scaffold_16",
        "Environment Name": "dqn_scaffold_16",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_16",
        "Environment Name": "dqn_scaffold_16",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_17a = [
    {
        "Model Name": "dqn_scaffold_17",
        "Environment Name": "dqn_scaffold_17",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_17",
        "Environment Name": "dqn_scaffold_17",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_18a = [
    {
        "Model Name": "dqn_scaffold_18",
        "Environment Name": "dqn_scaffold_18",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_18",
        "Environment Name": "dqn_scaffold_18",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

# For Symposium (06.06 onwards)

dqn_scaffold_19a = [
    {
        "Model Name": "dqn_scaffold_19",
        "Environment Name": "dqn_scaffold_19",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_19",
        "Environment Name": "dqn_scaffold_19",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_19b = [
    {
        "Model Name": "dqn_scaffold_19",
        "Environment Name": "dqn_scaffold_19",
        "Trial Number": 3,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_19",
        "Environment Name": "dqn_scaffold_19",
        "Trial Number": 4,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_nl_19a = [
    {
        "Model Name": "dqn_scaffold_nl_19",
        "Environment Name": "dqn_scaffold_nl_19",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_nl_19",
        "Environment Name": "dqn_scaffold_nl_19",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_nl_19b = [
    {
        "Model Name": "dqn_scaffold_nl_19",
        "Environment Name": "dqn_scaffold_nl_19",
        "Trial Number": 3,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": True,
    },
    {
        "Model Name": "dqn_scaffold_nl_19",
        "Environment Name": "dqn_scaffold_nl_19",
        "Trial Number": 4,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": True,
    },
]

dqn_scaffold_20a = [
    {
        "Model Name": "dqn_scaffold_20",
        "Environment Name": "dqn_scaffold_20",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_20",
        "Environment Name": "dqn_scaffold_20",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_21a = [
    {
        "Model Name": "dqn_scaffold_21",
        "Environment Name": "dqn_scaffold_21",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_21",
        "Environment Name": "dqn_scaffold_21",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_22a = [
    {
        "Model Name": "dqn_scaffold_22",
        "Environment Name": "dqn_scaffold_22",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_22",
        "Environment Name": "dqn_scaffold_22",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_22b = [
    {
        "Model Name": "dqn_scaffold_22",
        "Environment Name": "dqn_scaffold_22",
        "Trial Number": 3,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_22",
        "Environment Name": "dqn_scaffold_22",
        "Trial Number": 4,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_no_scaffold = [
    {
        "Model Name": "dqn_no_scaffold",
        "Environment Name": "dqn_no_scaffold",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_no_scaffold",
        "Environment Name": "dqn_no_scaffold",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

# To Continue 21.06.22

ppo_scaffold_18 = [
    {
        "Model Name": "ppo_scaffold_18",
        "Environment Name": "ppo_scaffold_18",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "ppo_scaffold_18",
        "Environment Name": "ppo_scaffold_18",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

ppo_scaffold_19 = [
    {
        "Model Name": "ppo_scaffold_19",
        "Environment Name": "ppo_scaffold_19",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "ppo_scaffold_19",
        "Environment Name": "ppo_scaffold_19",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

ppo_scaffold_20 = [
    {
        "Model Name": "ppo_scaffold_20",
        "Environment Name": "ppo_scaffold_20",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "ppo_scaffold_20",
        "Environment Name": "ppo_scaffold_20",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

ppo_scaffold_18a = [
    {
        "Model Name": "ppo_scaffold_18a",
        "Environment Name": "ppo_scaffold_18a",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "ppo_scaffold_18a",
        "Environment Name": "ppo_scaffold_18a",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

ppo_scaffold_20_bs = [
    {
        "Model Name": "ppo_scaffold_20_bs",
        "Environment Name": "ppo_scaffold_20_bs",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_23a = [
    {
        "Model Name": "dqn_scaffold_23",
        "Environment Name": "dqn_scaffold_23",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_23",
        "Environment Name": "dqn_scaffold_23",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_23b = [
    {
        "Model Name": "dqn_scaffold_23",
        "Environment Name": "dqn_scaffold_23",
        "Trial Number": 3,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_23",
        "Environment Name": "dqn_scaffold_23",
        "Trial Number": 4,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_24a = [
    {
        "Model Name": "dqn_scaffold_24",
        "Environment Name": "dqn_scaffold_24",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_24",
        "Environment Name": "dqn_scaffold_24",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_24b = [
    {
        "Model Name": "dqn_scaffold_24",
        "Environment Name": "dqn_scaffold_24",
        "Trial Number": 3,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_24",
        "Environment Name": "dqn_scaffold_24",
        "Trial Number": 4,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_dn_23a = [
    {
        "Model Name": "dqn_scaffold_dn_23",
        "Environment Name": "dqn_scaffold_dn_23",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_dn_23",
        "Environment Name": "dqn_scaffold_dn_23",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_dn_23b = [
    {
        "Model Name": "dqn_scaffold_dn_23",
        "Environment Name": "dqn_scaffold_dn_23",
        "Trial Number": 3,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_dn_23",
        "Environment Name": "dqn_scaffold_dn_23",
        "Trial Number": 4,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]


dqn_scaffold_25a = [
    {
        "Model Name": "dqn_scaffold_25",
        "Environment Name": "dqn_scaffold_25",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_25",
        "Environment Name": "dqn_scaffold_25",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_25b = [
    {
        "Model Name": "dqn_scaffold_25",
        "Environment Name": "dqn_scaffold_25",
        "Trial Number": 3,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_23",
        "Environment Name": "dqn_scaffold_23",
        "Trial Number": 4,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]



dqn_scaffold_26a = [
    {
        "Model Name": "dqn_scaffold_26",
        "Environment Name": "dqn_scaffold_26",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_26",
        "Environment Name": "dqn_scaffold_26",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_26b = [
    {
        "Model Name": "dqn_scaffold_26",
        "Environment Name": "dqn_scaffold_26",
        "Trial Number": 3,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_26",
        "Environment Name": "dqn_scaffold_26",
        "Trial Number": 4,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]


ppo_scaffold_22 = [
    {
        "Model Name": "ppo_scaffold_22",
        "Environment Name": "ppo_scaffold_22",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "ppo_scaffold_22",
        "Environment Name": "ppo_scaffold_22",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": True,
        "Learning Algorithm": "PPO",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_dnr_25 = [
    {
        "Model Name": "dqn_scaffold_dnr_25",
        "Environment Name": "dqn_scaffold_dnr_25",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_dnr_25",
        "Environment Name": "dqn_scaffold_dnr_25",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_dn_switch_25 = [
    {
        "Model Name": "dqn_scaffold_dn_switch_25",
        "Environment Name": "dqn_scaffold_dn_switch_25",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    # {
    #     "Model Name": "dqn_scaffold_dn_switch_25",
    #     "Environment Name": "dqn_scaffold_dn_switch_25",
    #     "Trial Number": 2,
    #     "Run Mode": "Training",
    #     "Tethered": False,
    #     "Realistic Bouts": True,
    #     "Continuous Actions": False,
    #     "Learning Algorithm": "DQN",
    #     "Priority": 1,
    #     "Using GPU": True,
    #     "monitor gpu": False,
    #     "Full Logs": True,
    #     "SB Emulator": False,
    #     "New Simulation": True,
    #     "Profile Speed": False,
    # },
]

dqn_scaffold_dn_switch_ = [
    {
        "Model Name": "dqn_scaffold_dn_switch",
        "Environment Name": "dqn_scaffold_dn_switch",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": False,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_27a = [
    {
        "Model Name": "dqn_scaffold_27",
        "Environment Name": "dqn_scaffold_27",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_27",
        "Environment Name": "dqn_scaffold_27",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_28a = [
    {
        "Model Name": "dqn_scaffold_28",
        "Environment Name": "dqn_scaffold_28",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_28",
        "Environment Name": "dqn_scaffold_28",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_29a = [
    {
        "Model Name": "dqn_scaffold_29",
        "Environment Name": "dqn_scaffold_29",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
    {
        "Model Name": "dqn_scaffold_29",
        "Environment Name": "dqn_scaffold_29",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_26_3 = [
    {
        "Model Name": "dqn_scaffold_26",
        "Environment Name": "dqn_scaffold_26",
        "Trial Number": 3,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_26_4 = [
    {
        "Model Name": "dqn_scaffold_26",
        "Environment Name": "dqn_scaffold_26",
        "Trial Number": 4,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_27_1 = [
    {
        "Model Name": "dqn_scaffold_27",
        "Environment Name": "dqn_scaffold_27",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_27_2 = [
    {
        "Model Name": "dqn_scaffold_27",
        "Environment Name": "dqn_scaffold_27",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_28_1 = [
    {
        "Model Name": "dqn_scaffold_28",
        "Environment Name": "dqn_scaffold_28",
        "Trial Number": 1,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

dqn_scaffold_28_2 = [
    {
        "Model Name": "dqn_scaffold_28",
        "Environment Name": "dqn_scaffold_28",
        "Trial Number": 2,
        "Run Mode": "Training",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": False,
        "Learning Algorithm": "DQN",
        "Priority": 1,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": False,
        "New Simulation": True,
        "Profile Speed": False,
    },
]

