naturalistic_assay_config = {
        "Model Name": "PLACEHOLDER",
        "Environment Name": "PLACEHOLDER",
        "Assay Configuration Name": "Behavioural-Data-Free",
        "Trial Number": "PLACEHOLDER",
        "Checkpoint": None,
        "Run Mode": "Assay",
        "Tethered": False,
        "Realistic Bouts": True,
        "Continuous Actions": "PLACEHOLDER",
        "Learning Algorithm": "PLACEHOLDER",
        "Priority": 2,
        "Using GPU": True,
        "monitor gpu": False,
        "Full Logs": True,
        "SB Emulator": True,
        "set random seed": False,
        "New Simulation": True,
        "Assays": [
            {
                "assay id": "Naturalistic-1",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-2",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-3",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-4",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-5",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-6",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-7",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-8",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-9",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-10",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-11",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-12",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-13",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-14",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-15",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-16",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-17",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-18",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-19",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-20",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-21",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-22",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-23",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-24",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-25",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-26",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-27",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-28",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-29",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-30",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-31",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-32",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-33",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-34",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-35",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-36",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-37",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-38",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-39",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            {
                "assay id": "Naturalistic-40",
                "stimulus paradigm": "Naturalistic",
                "duration": 2000,
                "Tethered": False,
                "save frames": True,
                "use_mu": True,
                "save stimuli": False,
                "random positions": False,
                "reset": False,
                "background": None,
                "moving": False,
                "collisions": True,
                "recordings": ["rnn state", "environmental positions", "observation", "internal state"],
                "behavioural recordings": ["environmental positions", "observation"],
                "network recordings": ["rnn state", "internal state"],
                "ablations": []
            },
            ],
    }

